In [4]:
import numpy as np

# Create a 1D array of 12 elements (0 to 11)
data = np.arange(12) 
print("1D Array:", data)

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
# Change 12 elements into a 3x4 Matrix
matrix_2d = data.reshape(6,2)
print("\n2D Matrix (3 rows, 4 columns):\n", matrix_2d)

# Change 12 elements into a 3D Tensor (2 layers, 3 rows, 2 columns)
# This is how AI sees Color Images (Red, Green, Blue layers)
tensor_3d = data.reshape(3,2,2)
print("\n3D Tensor (Format for Images):\n", tensor_3d)


2D Matrix (3 rows, 4 columns):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

3D Tensor (Format for Images):
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [6]:
# Create two 2x2 matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform Matrix Multiplication
# Rule: (Row of A) * (Column of B)
result = np.dot(A, B) 
print("\nAI Logic Result:\n", result) 
# Expected Output: [[19, 22], [43, 50]]


AI Logic Result:
 [[19 22]
 [43 50]]


In [7]:
 # TRY THIS: Try to reshape 12 elements into a 5x5 matrix
try:
    fail_test = data.reshape(5, 5)
except ValueError as e:
    print(f"ERROR CAUGHT: {e}")

ERROR CAUGHT: cannot reshape array of size 12 into shape (5,5)


In [13]:
# Create a 2x3 matrix
original = np.array([[1, 2, 3], [4, 5, 6]])
print("Original (2x3):\n", original)

# Flip it (Transpose)
flipped = original.T 
print("\nFlipped (3x2):\n", flipped)

Original (2x3):
 [[1 2 3]
 [4 5 6]]

Flipped (3x2):
 [[1 4]
 [2 5]
 [3 6]]
